# Generated by Django 4.1 on 2023-04-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_desc_product_esc_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='esc',
            new_name='dsc',
        ),
    ]
