# Generated by Django 3.2.8 on 2023-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_esc_product_dsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dsc',
            field=models.CharField(max_length=1000),
        ),
    ]
